pool:
  vmImage: 'windows-2019'

trigger:
  batch: true
  branches:
    include:
      - master
      - course-update

steps:

- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core sdk 2.2.300'
  inputs:
    version: 2.2.300

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: M6/ECommerce.sln
    configuration: release
    platform: x64

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: M6/ECommerce/ECommerce.sfproj
    arguments: '-c release /t:Package /p:PackageLocation=$(build.artifactstagingdirectory)\pkg'
    configuration: release
    platform: x64

- task: ServiceFabricUpdateManifests@2
  displayName: 'Update Service Fabric Manifests (Manifest versions)'
  inputs:
    applicationPackagePath: '$(build.artifactstagingdirectory)\pkg'
    versionSuffix: '.$(build.buildnumber)'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)\projectartifacts'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: |
     **\PublishProfiles\*.xml
     **\ApplicationParameters\*.xml
    TargetFolder: '$(build.artifactstagingdirectory)\publishprofiles'
  condition: succeededOrFailed()

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()

