pool:
  vmImage: 'windows-2019'

trigger:
  batch: true
  branches:
    include:
      - master
      - course-update

steps:

- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core sdk 2.2.300'
  inputs:
    version: 2.2.300

- task: VSBuild@1
  displayName: 'Build solution **\*.sln'
  inputs:
    solution: M6/ECommerce.sln
    platform: x64
    configuration: release

- task: VSBuild@1
  displayName: 'Build solution **\*.sfproj'
  inputs:
    solution: M6/ECommerce/ECommerce.sfproj
    msbuildArgs: '/t:Package /p:PackageLocation=$(build.artifactstagingdirectory)\pkg'
    platform: x64
    configuration: release

- task: ServiceFabricUpdateManifests@2
  displayName: 'Update Service Fabric Manifest Versions'
  inputs:
    applicationPackagePath: '$(build.artifactstagingdirectory)\pkg'
    versionSuffix: '.$(build.buildnumber)'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)\projectartifacts'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: |
     **\PublishProfiles\*.xml
     **\ApplicationParameters\*.xml
    TargetFolder: '$(build.artifactstagingdirectory)\publishprofiles'
  condition: succeededOrFailed()

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()

