pool:
  vmImage: 'windows-2019'

trigger:
  batch: true
  branches:
    include:
      - master
      - course-update

steps:

- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core sdk 2.2.300'
  inputs:
    version: 2.2.300

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: M6/ECommerce.sln
    arguments: '-c release /t:Publish'


